name: Go Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'  # Replace with your Go version
        
    - name: Install gocovmerge
      run: |
        go install github.com/wadey/gocovmerge@latest
        echo "GOPATH=$HOME/go" >> $GITHUB_ENV
        echo "$HOME/go/bin" >> $GITHUB_PATH    

    - name: Test with coverage (main)
      run: go test -coverprofile=coverage_main.out ./...

    - name: Test with coverage (builtins)
      run: go test -coverprofile=coverage_builtins.out ./builtins

    - name: Merge coverage profiles
      run: gocovmerge coverage_main.out coverage_builtins.out > coverage_merged.out

    - name: Generate HTML coverage report
      run: go tool cover -html=coverage_merged.out -o coverage.html

    - name: Display function-level coverage
      run: go tool cover -func=coverage_merged.out

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: 53bef8ac-003a-464a-bd03-3480cb839e70
      with:
        file: ./coverage_merged.out
        fail_ci_if_error: true
